# Generated by Django 3.1.2 on 2020-10-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apostador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='apostadorusuario', serialize=False, to='auth.user')),
                ('credito', models.DecimalField(decimal_places=2, default=10.0, editable=False, max_digits=8)),
                ('premiacao_ganha', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8)),
                ('qtd_vitorias', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Apostadores',
            },
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('qtd_titulos', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Seleções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_desafiante', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('gols_visitante', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('estadio', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField()),
                ('selecao_desafiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaodesafiante', to='bolao_app.selecao')),
                ('selecao_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selecaovisitante', to='bolao_app.selecao')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('premiacao', models.FloatField(default=0.0, editable=False)),
                ('valor_disputado', models.FloatField(default=0.0, editable=False)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao_app.partida')),
            ],
            options={
                'verbose_name': 'Bolõe',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ApostadorVencedorBolao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao_app.apostador')),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao_app.bolao')),
            ],
            options={
                'verbose_name_plural': 'Apostador(es) vencedor(es) bolões',
                'unique_together': {('apostador', 'bolao')},
            },
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_gols_desafiante', models.PositiveSmallIntegerField()),
                ('qtd_gols_visitante', models.PositiveSmallIntegerField()),
                ('valor', models.FloatField(default=5.0, editable=False)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao_app.apostador')),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao_app.bolao')),
            ],
            options={
                'unique_together': {('apostador', 'bolao')},
            },
        ),
    ]
