# Generated by Django 3.1.2 on 2020-10-24 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_app', '0002_auto_20201021_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolao',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Bolões'},
        ),
        migrations.AlterModelOptions(
            name='partida',
            options={'ordering': ['-data_hora_inicio']},
        ),
        migrations.RenameField(
            model_name='partida',
            old_name='data_hora',
            new_name='data_hora_inicio',
        ),
        migrations.AddField(
            model_name='partida',
            name='data_hora_fim',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apostador',
            name='premiacao_ganha',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='apostador',
            name='qtd_vitorias',
            field=models.PositiveSmallIntegerField(blank=True, default=0, editable=False),
        ),
    ]
