# Generated by Django 3.1.2 on 2022-04-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao_app', '0005_auto_20201025_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostador',
            name='premiacao_ganha',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='apostador',
            name='qtd_vitorias',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gols_desafiante',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='gols_visitante',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
